.TH "bleDeviceInfo" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bleDeviceInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ble_devinfo\&.h>\fP
.PP
Inherits \fBCPeripheral\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbleDeviceInfo\fP (\fBbleSerial\fP &ble)"
.br
.ti -1c
.RI "int \fBsetManufactureName\fP (LPCTSTR str)"
.br
.ti -1c
.RI "int \fBsetModelNumber\fP (LPCTSTR str)"
.br
.ti -1c
.RI "int \fBsetSerialNumber\fP (LPCTSTR str)"
.br
.ti -1c
.RI "int \fBsetFirmwareRevison\fP (LPCTSTR str)"
.br
.ti -1c
.RI "int \fBsetHardwareRevision\fP (LPCTSTR str)"
.br
.ti -1c
.RI "void \fBsetSystemId\fP (\fBSYS_ID_T\fP &sysId)"
.br
.ti -1c
.RI "void \fBsetPnP\fP (VID_SOURCE_T src, uint16_t vendorId, uint16_t productId, uint16_t productVersion)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBbleSerial\fP * \fBm_ble\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bleDeviceInfo::bleDeviceInfo (\fBbleSerial\fP &ble)"

.SH "Member Function Documentation"
.PP 
.SS "int bleDeviceInfo::setManufactureName (LPCTSTRstr)"

.SS "int bleDeviceInfo::setModelNumber (LPCTSTRstr)"

.SS "int bleDeviceInfo::setSerialNumber (LPCTSTRstr)"

.SS "int bleDeviceInfo::setFirmwareRevison (LPCTSTRstr)"

.SS "int bleDeviceInfo::setHardwareRevision (LPCTSTRstr)"

.SS "void bleDeviceInfo::setSystemId (\fBSYS_ID_T\fP &sysId)"

.SS "void bleDeviceInfo::setPnP (VID_SOURCE_Tsrc, uint16_tvendorId, uint16_tproductId, uint16_tproductVersion)"

.SH "Member Data Documentation"
.PP 
.SS "\fBbleSerial\fP* bleDeviceInfo::m_ble\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
