.TH "bleProximity" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bleProximity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'class/ble_proximity\&.h'\fP
.PP
Inherits \fBCPeripheral\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbleProximity\fP (\fBbleSerial\fP &ble)"
.br
.ti -1c
.RI "virtual void \fBonAlert\fP (uint8_t level)"
.br
.ti -1c
.RI "virtual void \fBonLinkLoss\fP (uint8_t level)"
.br
.ti -1c
.RI "virtual bool \fBsendEvent\fP (uint8_t level)"
.br
.ti -1c
.RI "virtual void \fBsetTxPowerLevel\fP (int8_t dBm)"
.br
.ti -1c
.RI "virtual bool \fBisAvailable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBbleProximity\fP provide 'Immediate Alert' and 'Link Loss' services\&. The \fBbleProximity\fP enables proximity monitoring between two devices\&.
.br
 See Also:
.br
 \fCProximity Profile (PXP)\fP 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "bleProximity::bleProximity (\fBbleSerial\fP &ble)"
\fBbleProximity\fP constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIble\fP is a \fBbleSerial\fP class object\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual void bleProximity::onAlert (uint8_tlevel)\fC [virtual]\fP"
onAlert event is call by BLE task\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP is an uint8_t type value, 0=No Alert, 1=Mild Alert, 2=High Alert, 3-255 reserved\&. 
.RE
.PP
\fBRemarks:\fP
.RS 4
The onAlert will be implemented by the \fBbleProximity\fP class\&. 
.RE
.PP
\fBNote:\fP
.RS 4
The event is defined in the Immediate service of BLE\&. The Alert Level characteristic is a control point that allows a peer to command this device to alert to a given level\&. 
.RE
.PP

.SS "virtual void bleProximity::onLinkLoss (uint8_tlevel)\fC [virtual]\fP"
onLinkLoss event is call by BLE task\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP is an uint8_t type value, 0=No Alert, 1=Mild Alert, 2=High Alert, 3-255 reserved\&. 
.RE
.PP
\fBRemarks:\fP
.RS 4
The onLinkLose will be implemented by the bleProxmity class\&. 
.RE
.PP
\fBNote:\fP
.RS 4
The event is defined in the Link-Lose service of BLE\&. The Alert Level characteristic is used to expose the current link loss alert level that is used to determine how the device alerts when the link is lost\&. 
.RE
.PP

.SS "virtual bool bleProximity::sendEvent (uint8_tlevel)\fC [virtual]\fP"
Send alert event to remote (App)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIlevel\fP is an uint8_t type value to indicate BLE devie alert level\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
true, if send alert event successful\&. otherwise, if send alert event failed\&. 
.RE
.PP

.SS "virtual void bleProximity::setTxPowerLevel (int8_tdBm)\fC [virtual]\fP"
setTxPowerLevel exposes a device’s current transmit power level when in a connection\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdBm\fP is a signed integer and range from +20dBm to -120dBm 
.RE
.PP

.SS "virtual bool bleProximity::isAvailable ()\fC [virtual]\fP"
Use isAvailable to check the service whether opened by remote (App)\&. 
.PP
\fBReturns:\fP
.RS 4
true, if service is available\&. otherwise, the service is not in used\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
