.TH "CBus" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CBus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'class/bus\&.h'\fP
.PP
Inherits \fBCPeripheral\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCBus\fP (PIN_NAME_T \fBpin\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBoutput\fP ()"
.br
.ti -1c
.RI "void \fBinput\fP (PIN_INPUT_MODE_T mode=INTERNAL_PULL_UP)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint32_t val)"
.br
.ti -1c
.RI "virtual uint32_t \fBread\fP ()"
.br
.ti -1c
.RI "\fBCPin\fP & \fBpin\fP (int index)"
.br
.ti -1c
.RI "\fBoperator uint32_t\fP ()"
.br
.ti -1c
.RI "void \fBoperator=\fP (uint32_t val)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (uint32_t val)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (uint32_t val)"
.br
.ti -1c
.RI "\fBCPin\fP & \fBoperator[]\fP (int index)"
.br
.ti -1c
.RI "int \fBcount\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A digital input/output bus, used for reading/writing the state of a collection of pins\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CBus::CBus (PIN_NAME_Tpin, \&.\&.\&.)"
Constructs a \fBCBus\fP object to connect to the specified pins\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpin\fP \&.\&.\&. are PIN_NAME_T to specified one or more pins to the \fBCBus\fP\&.
.RE
.PP
.PP
.nf
Example:
        CBus bus(P21, P22, P23, P24, END);  // Collect P21~P24 in the CBus object\&.
        bus\&.output();                       // Set the bus as output pins\&.
.fi
.PP
 
.PP
\fBRemarks:\fP
.RS 4
to 'END' of the pin arguments is MUST!! 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void CBus::output ()"
Call the member function to set the bus as output pins\&. 
.PP
\fBParameters:\fP
.RS 4
\fImode\fP is a PIN_OUTPUT_MODE_T, default is OPEN_DRAIN (provide current)\&. 
.RE
.PP

.SS "void CBus::input (PIN_INPUT_MODE_Tmode = \fCINTERNAL_PULL_UP\fP)"
Call the member function to set the bus as input pins 
.PP
\fBParameters:\fP
.RS 4
\fImode\fP is a PIN_INPUT_MODE_T, default is INTERNAL_PUTT_UP\&. 
.RE
.PP

.SS "virtual void CBus::write (uint32_tval)\fC [virtual]\fP"
Call the member function to write a value to the bus\&. 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP is a unsigned integer to map the bit wide value to pins\&. 
.RE
.PP

.SS "virtual uint32_t CBus::read ()\fC [virtual]\fP"
Call the member function to retrieve a value from pins\&. 
.PP
\fBReturns:\fP
.RS 4
a unsigned integer value that map the bit-wide of pins\&. 
.RE
.PP

.SS "\fBCPin\fP& CBus::pin (intindex)"
Call the member function to retrieve a identity pin from bus\&. 
.PP
\fBReturns:\fP
.RS 4
\fBCPin\fP 
.RE
.PP

.SS "CBus::operator uint32_t ()\fC [inline]\fP"
A shorthand for read
.PP
.PP
.nf
Example:
        CBus bus(P21, P22, P23, P24, END);  // Collect P21~P24 in the CBus object\&.
        bus\&.input();                        // Set the bus as input pins\&.
        uint32_t val = bus;                 // Read a value from bus\&.
.fi
.PP
 
.SS "void CBus::operator= (uint32_tval)\fC [inline]\fP"
A shorthand for write
.PP
.PP
.nf
Example:
        CBus bus(P21, P22, P23, P24, END);  // Collect P21~P24 in the CBus object\&.
        bus\&.output();                       // Set the bus as output pins\&.
        bus = 0x05;                         // Write 0x05 to bus\&.
.fi
.PP
 
.SS "bool CBus::operator== (uint32_tval)\fC [inline]\fP"
A shorthand for equal to\&.\&.\&. 
.PP
\fBReturns:\fP
.RS 4
true if the bus==val, otherwise, failed\&. 
.RE
.PP

.SS "bool CBus::operator!= (uint32_tval)\fC [inline]\fP"
A shorthand for not equal to\&.\&.\&. 
.PP
\fBReturns:\fP
.RS 4
true if the bus not equal the val; otherwise, failed\&. 
.RE
.PP

.SS "\fBCPin\fP& CBus::operator[] (intindex)\fC [inline]\fP"
A shorthand for array 
.PP
\fBReturns:\fP
.RS 4
\fBCPin\fP
.RE
.PP
.PP
.nf
Example:
        CBus bus(P21, P22, P23, P24, END);  // Collect P21~P24 in the CBus object\&.
        bus\&.output();                       // Set the bus as output pins\&.
    bus[2] = LOW;                       // Set P23 is LOW\&.
.fi
.PP
 
.SS "int CBus::count ()\fC [inline]\fP"
Call the member function to retrieve the number of pins in the bus\&. 
.PP
\fBReturns:\fP
.RS 4
integer value\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
