.TH "CDC_LINE_CODING_T" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDC_LINE_CODING_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <usb_cdc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBdwDTERate\fP"
.br
.ti -1c
.RI "uint8_t \fBbCharFormat\fP"
.br
.ti -1c
.RI "uint8_t \fBbParityType\fP"
.br
.ti -1c
.RI "uint8_t \fBbDataBits\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32_t CDC_LINE_CODING_T::dwDTERate"

.SS "uint8_t CDC_LINE_CODING_T::bCharFormat"

.SS "uint8_t CDC_LINE_CODING_T::bParityType"

.SS "uint8_t CDC_LINE_CODING_T::bDataBits"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
