.TH "CDebug" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CDebug \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <debug\&.h>\fP
.PP
Inherits \fBCThread\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCDebug\fP (\fBCStream\fP &s)"
.br
.ti -1c
.RI "virtual bool \fBstart\fP ()"
.br
.ti -1c
.RI "virtual void \fBwaitToDebugMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBprintf\fP (LPCTSTR format, va_list varg)"
.br
.ti -1c
.RI "virtual void \fBprintf\fP (LPCTSTR format,\&.\&.\&.)"
.br
.ti -1c
.RI "virtual void \fBprintln\fP (LPCTSTR format,\&.\&.\&.)"
.br
.ti -1c
.RI "virtual void \fBprintln\fP (int value)"
.br
.ti -1c
.RI "virtual void \fBprintln\fP (uint32_t value)"
.br
.ti -1c
.RI "virtual void \fBprintln\fP (float value)"
.br
.ti -1c
.RI "virtual int \fBbreakpoint\fP (LPCTSTR desc=NULL)"
.br
.ti -1c
.RI "virtual void \fBprintln\fP (\fBCString\fP &str)"
.br
.ti -1c
.RI "virtual bool \fBisDebugMode\fP ()"
.br
.ti -1c
.RI "virtual int \fBisAnyKey\fP ()"
.br
.ti -1c
.RI "virtual void \fBputc\fP (int c)"
.br
.ti -1c
.RI "int \fBbp\fP ()"
.br
.ti -1c
.RI "\fBoperator bool\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrun\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCStream\fP * \fBm_stream\fP"
.br
.ti -1c
.RI "\fBCShell\fP \fBm_shell\fP"
.br
.ti -1c
.RI "\fBCMutex\fP \fBm_mutex\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CDebug::CDebug (\fBCStream\fP &s)"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool CDebug::start ()\fC [virtual]\fP"
Call the member function to start the thread\&. 
.PP
\fBNote:\fP
.RS 4
the \fBstart()\fP is an overload member function of \fBCThread\fP\&. 
.RE
.PP

.PP
Reimplemented from \fBCThread\fP\&.
.SS "virtual void CDebug::waitToDebugMode ()\fC [virtual]\fP"

.SS "virtual void CDebug::printf (LPCTSTRformat, va_listvarg)\fC [virtual]\fP"

.SS "virtual void CDebug::printf (LPCTSTRformat, \&.\&.\&.)\fC [virtual]\fP"

.SS "virtual void CDebug::println (LPCTSTRformat, \&.\&.\&.)\fC [virtual]\fP"

.SS "virtual void CDebug::println (intvalue)\fC [virtual]\fP"

.SS "virtual void CDebug::println (uint32_tvalue)\fC [virtual]\fP"

.SS "virtual void CDebug::println (floatvalue)\fC [virtual]\fP"

.SS "virtual int CDebug::breakpoint (LPCTSTRdesc = \fCNULL\fP)\fC [virtual]\fP"

.SS "virtual void CDebug::println (\fBCString\fP &str)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual bool CDebug::isDebugMode ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual int CDebug::isAnyKey ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void CDebug::putc (intc)\fC [virtual]\fP"

.SS "int CDebug::bp ()\fC [inline]\fP"

.SS "CDebug::operator bool ()\fC [inline]\fP"

.SS "virtual void CDebug::run ()\fC [protected]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCStream\fP* CDebug::m_stream\fC [protected]\fP"

.SS "\fBCShell\fP CDebug::m_shell\fC [protected]\fP"

.SS "\fBCMutex\fP CDebug::m_mutex\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
