.TH "CI2CSlave" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CI2CSlave \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <i2c\&.h>\fP
.PP
Inherits \fBCI2C\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCI2CSlave\fP (uint8_t slaveAddr)"
.br
.ti -1c
.RI "virtual I2C_ERROR_T \fBreadwrite\fP (uint8_t slaveAddr, void *txbuf, int txsize, void *rxbuf, int rxsize)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CI2CSlave::CI2CSlave (uint8_tslaveAddr)"

.SH "Member Function Documentation"
.PP 
.SS "virtual I2C_ERROR_T CI2CSlave::readwrite (uint8_tslaveAddr, void *txbuf, inttxsize, void *rxbuf, intrxsize)\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
