.TH "CListT< CType >" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CListT< CType > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <list\&.h>\fP
.PP
Inherits \fBCList\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual LIST_POS \fBaddHeadT\fP (CType *elem)"
.br
.ti -1c
.RI "virtual LIST_POS \fBaddTailT\fP (CType *elem)"
.br
.ti -1c
.RI "virtual CType * \fBgetHeadT\fP ()"
.br
.ti -1c
.RI "virtual CType * \fBgetTailT\fP ()"
.br
.ti -1c
.RI "virtual CType * \fBgetAtT\fP (LIST_POS pos)"
.br
.ti -1c
.RI "virtual CType * \fBremoveHeadT\fP ()"
.br
.ti -1c
.RI "virtual CType * \fBremoveTailT\fP ()"
.br
.ti -1c
.RI "virtual void \fBremoveAtT\fP (CType *elem)"
.br
.ti -1c
.RI "virtual void \fBremoveAllT\fP (bool free_elem=false)"
.br
.ti -1c
.RI "virtual LIST_POS \fBinsertBeforeT\fP (LIST_POS pos, CType *elem)"
.br
.ti -1c
.RI "virtual LIST_POS \fBinsertAfterT\fP (LIST_POS pos, CType *elem)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<class CType > virtual LIST_POS \fBCListT\fP< CType >::addHeadT (CType *elem)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual LIST_POS \fBCListT\fP< CType >::addTailT (CType *elem)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual CType* \fBCListT\fP< CType >::getHeadT ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual CType* \fBCListT\fP< CType >::getTailT ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual CType* \fBCListT\fP< CType >::getAtT (LIST_POSpos)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual CType* \fBCListT\fP< CType >::removeHeadT ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual CType* \fBCListT\fP< CType >::removeTailT ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual void \fBCListT\fP< CType >::removeAtT (CType *elem)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual void \fBCListT\fP< CType >::removeAllT (boolfree_elem = \fCfalse\fP)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual LIST_POS \fBCListT\fP< CType >::insertBeforeT (LIST_POSpos, CType *elem)\fC [inline]\fP, \fC [virtual]\fP"

.SS "template<class CType > virtual LIST_POS \fBCListT\fP< CType >::insertAfterT (LIST_POSpos, CType *elem)\fC [inline]\fP, \fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
