.TH "CObject" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CObject \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <object\&.h>\fP
.PP
Inherited by \fBCEventBit\fP, \fBCList\fP, \fBCMailBox\fP, \fBCMutex\fP, \fBCPeripheral\fP\fC [virtual]\fP, \fBCRC16\fP, \fBCSemaphore\fP, \fBCSmallPrintf\fP, \fBCStream\fP, \fBCThread\fP\fC [virtual]\fP, and \fBCTimeout\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCObject\fP ()"
.br
.ti -1c
.RI "virtual \fB~CObject\fP ()"
.br
.ti -1c
.RI "virtual bool \fBisThread\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CObject::CObject ()"

.SS "virtual CObject::~CObject ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool CObject::isThread ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBCThread\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
