.TH "CPeripheral" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPeripheral \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <peripheral\&.h>\fP
.PP
Inherits \fBCObject\fP\&.
.PP
Inherited by \fBbleBatteryLevel\fP\fC [virtual]\fP, \fBbleDeviceInfo\fP, \fBbleHealthThermometer\fP, \fBbleHeartRate\fP, \fBbleProximity\fP, \fBCAdc\fP, \fBCBus\fP, \fBCI2C\fP, \fBCPin\fP, \fBCPowerSave\fP, \fBCPwm\fP, \fBCSPI\fP, \fBCTimer\fP, \fBCWatchdog\fP, and \fBEEPROM\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
