.TH "CPin" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPin \- 
.PP
pin output/input control\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'class/pin\&.h'\fP
.PP
Inherits \fBCPeripheral\fP\&.
.PP
Inherited by \fBCPinINT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCPin\fP (PIN_NAME_T p)"
.br
.ti -1c
.RI "virtual void \fBoutput\fP (PIN_OUTPUT_MODE_T mode=NOT_OPEN, PIN_LEVEL_T defValue=LOW)"
.br
.ti -1c
.RI "virtual void \fBinput\fP (PIN_INPUT_MODE_T mode=INTERNAL_PULL_UP)"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (PIN_LEVEL_T val)"
.br
.ti -1c
.RI "virtual PIN_LEVEL_T \fBread\fP ()"
.br
.ti -1c
.RI "virtual void \fBinvert\fP ()"
.br
.ti -1c
.RI "void \fBoperator=\fP (PIN_LEVEL_T val)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBCPin\fP &pin)"
.br
.ti -1c
.RI "\fBoperator PIN_LEVEL_T\fP ()"
.br
.ti -1c
.RI "PIN_LEVEL_T \fBoperator!\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (PIN_LEVEL_T val)"
.br
.ti -1c
.RI "bool \fBoperator!=\fP (PIN_LEVEL_T val)"
.br
.ti -1c
.RI "PIN_NAME_T \fBname\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
pin output/input control\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CPin::CPin (PIN_NAME_Tp)"
Constructs a \fBCPin\fP object to connect to the specified pin\&. 
.PP
\fBParameters:\fP
.RS 4
\fIp\fP \&.\&.\&. are PIN_NAME_T to specified a pin to the object\&.
.RE
.PP
.PP
.nf
Example:
        CPin key(P21);      // Create a key object to connect to pin 21\&.
        key\&.input();        // set the key object as a input\&.

        if ( key==LOW ) {   // check the pin level

        }
.fi
.PP
.PP
\fBRemarks:\fP
.RS 4
to 'END' of the pin arguments is MUST!! 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual void CPin::output (PIN_OUTPUT_MODE_Tmode = \fCNOT_OPEN\fP, PIN_LEVEL_TdefValue = \fCLOW\fP)\fC [virtual]\fP"

.SS "virtual void CPin::input (PIN_INPUT_MODE_Tmode = \fCINTERNAL_PULL_UP\fP)\fC [virtual]\fP"

.SS "virtual void CPin::write (PIN_LEVEL_Tval)\fC [virtual]\fP"

.SS "virtual PIN_LEVEL_T CPin::read ()\fC [virtual]\fP"

.SS "virtual void CPin::invert ()\fC [virtual]\fP"

.SS "void CPin::operator= (PIN_LEVEL_Tval)\fC [inline]\fP"

.SS "void CPin::operator= (\fBCPin\fP &pin)\fC [inline]\fP"

.SS "CPin::operator PIN_LEVEL_T ()\fC [inline]\fP"

.SS "PIN_LEVEL_T CPin::operator! ()\fC [inline]\fP"

.SS "bool CPin::operator== (PIN_LEVEL_Tval)\fC [inline]\fP"

.SS "bool \fBCPin::operator!\fP= (PIN_LEVEL_Tval)\fC [inline]\fP"

.SS "PIN_NAME_T CPin::name ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
