.TH "CPinINT" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CPinINT \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pinint\&.h>\fP
.PP
Inherits \fBCPin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCPinINT\fP (PIN_NAME_T pin, EDGE_STATE_T edge, PIN_INPUT_MODE_T mode=INTERNAL_PULL_UP)"
.br
.ti -1c
.RI "\fBCPinINT\fP (PIN_NAME_T pin, PIN_LEVEL_T level, PIN_INPUT_MODE_T mode=INTERNAL_PULL_UP)"
.br
.ti -1c
.RI "virtual void \fBenable\fP ()"
.br
.ti -1c
.RI "virtual void \fBdisable\fP ()"
.br
.ti -1c
.RI "void \fBbegin\fP ()"
.br
.ti -1c
.RI "void \fBend\fP ()"
.br
.ti -1c
.RI "virtual bool \fBwait\fP (uint32_t tm=MAX_DELAY_TIME)"
.br
.ti -1c
.RI "virtual void \fBrelease\fP ()"
.br
.ti -1c
.RI "void \fBasWeakupSource\fP ()"
.br
.ti -1c
.RI "virtual \fB~CPinINT\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCSemaphore\fP \fBm_semIrq\fP"
.br
.ti -1c
.RI "uint32_t \fBm_event\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBassign\fP (PIN_NAME_T pin, PIN_INPUT_MODE_T mode)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetFreeChannel\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBm_ch\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CPinINT::CPinINT (PIN_NAME_Tpin, EDGE_STATE_Tedge, PIN_INPUT_MODE_Tmode = \fCINTERNAL_PULL_UP\fP)"

.SS "CPinINT::CPinINT (PIN_NAME_Tpin, PIN_LEVEL_Tlevel, PIN_INPUT_MODE_Tmode = \fCINTERNAL_PULL_UP\fP)"

.SS "virtual CPinINT::~CPinINT ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void CPinINT::enable ()\fC [virtual]\fP"

.SS "virtual void CPinINT::disable ()\fC [virtual]\fP"

.SS "void CPinINT::begin ()\fC [inline]\fP"

.SS "void CPinINT::end ()\fC [inline]\fP"

.SS "virtual bool CPinINT::wait (uint32_ttm = \fCMAX_DELAY_TIME\fP)\fC [virtual]\fP"

.SS "virtual void CPinINT::release ()\fC [virtual]\fP"

.SS "void CPinINT::asWeakupSource ()"

.SS "virtual void CPinINT::assign (PIN_NAME_Tpin, PIN_INPUT_MODE_Tmode)\fC [protected]\fP, \fC [virtual]\fP"

.SS "static int CPinINT::getFreeChannel ()\fC [static]\fP, \fC [protected]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBCSemaphore\fP CPinINT::m_semIrq"

.SS "uint32_t CPinINT::m_event"

.SS "int CPinINT::m_ch\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
