.TH "CSmallPrintf" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSmallPrintf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <smallprintf\&.h>\fP
.PP
Inherits \fBCObject\fP\&.
.PP
Inherited by \fBConsole\fP, and \fBCString\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSmallPrintf\fP ()"
.br
.ti -1c
.RI "int \fBprintf\fP (LPCTSTR format,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBprintf\fP (LPCTSTR format, va_list args)"
.br
.ti -1c
.RI "int \fBputv\fP (int val)"
.br
.ti -1c
.RI "int \fBputv\fP (unsigned val)"
.br
.ti -1c
.RI "int \fBputv\fP (double val)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSmallPrintf::CSmallPrintf ()"

.SH "Member Function Documentation"
.PP 
.SS "int CSmallPrintf::printf (LPCTSTRformat, \&.\&.\&.)"

.SS "int CSmallPrintf::printf (LPCTSTRformat, va_listargs)"

.SS "int CSmallPrintf::putv (intval)"

.SS "int CSmallPrintf::putv (unsignedval)"

.SS "int CSmallPrintf::putv (doubleval)"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
