.TH "CSpiMaster" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CSpiMaster \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spi\&.h>\fP
.PP
Inherits \fBCSPI\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSpiMaster\fP (PIN_NAME_T selPin)"
.br
.ti -1c
.RI "virtual int \fBreadwrite\fP (void *txbuf, void *rxbuf, uint32_t length)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBCPin\fP \fBm_cs\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CSpiMaster::CSpiMaster (PIN_NAME_TselPin)"

.SH "Member Function Documentation"
.PP 
.SS "virtual int CSpiMaster::readwrite (void *txbuf, void *rxbuf, uint32_tlength)\fC [virtual]\fP"

.PP
Reimplemented from \fBCSPI\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCPin\fP CSpiMaster::m_cs\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
