.TH "CStream" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CStream \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'class/stream\&.h'\fP
.PP
Inherits \fBCObject\fP\&.
.PP
Inherited by \fBbleSerial\fP, \fBCSerial\fP, and \fBusbCDC\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCStream\fP ()"
.br
.ti -1c
.RI "virtual \fB~CStream\fP ()"
.br
.ti -1c
.RI "virtual int \fBreadable\fP ()"
.br
.ti -1c
.RI "int \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An abstract class, to define the serial stream input and output interface\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CStream::CStream ()"
\fBCStream\fP constructor 
.SS "virtual CStream::~CStream ()\fC [virtual]\fP"
\fBCStream\fP destructor 
.SH "Member Function Documentation"
.PP 
.SS "virtual int CStream::readable ()\fC [inline]\fP, \fC [virtual]\fP"
Determine how many data bytes are available to read\&. 
.PP
\fBReturns:\fP
.RS 4
A value to indicate how many data byte is available in the input buffer\&. 
.RE
.PP
\fBRemarks:\fP
.RS 4
the pure virtual function have to implement by child class\&. 
.RE
.PP

.PP
Reimplemented in \fBbleSerial\fP, \fBCSerial\fP, and \fBusbCDC\fP\&.
.SS "int CStream::read ()\fC [inline]\fP"
An inline function to read a character from input buffer of stream\&. 
.PP
\fBReturns:\fP
.RS 4
the character value, the character size is one byte\&. 
.RE
.PP
\fBNote:\fP
.RS 4
The inline function is a overload function to call to the \fBread()\fP member\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
