.TH "EEPROM" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EEPROM \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eeprom\&.h>\fP
.PP
Inherits \fBCPeripheral\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBread\fP (unsigned addr, void *buf, unsigned size)"
.br
.ti -1c
.RI "static bool \fBwrite\fP (unsigned addr, void *buf, unsigned size)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "static bool EEPROM::read (unsignedaddr, void *buf, unsignedsize)\fC [static]\fP"

.SS "static bool EEPROM::write (unsignedaddr, void *buf, unsignedsize)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
