.TH "fifo_t" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fifo_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fifo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBhead\fP"
.br
.ti -1c
.RI "int \fBtail\fP"
.br
.ti -1c
.RI "uint8_t * \fBbuf\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int fifo_t::size"

.SS "int fifo_t::head"

.SS "int fifo_t::tail"

.SS "uint8_t* fifo_t::buf"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
