.TH "h_thermo_temp_measure_t" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
h_thermo_temp_measure_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ble_ht\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.ti -1c
.RI "uint8_t \fBmeasurement\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBtime_type\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Temperature measurement structure 
.SH "Member Data Documentation"
.PP 
.SS "uint8_t h_thermo_temp_measure_t::flags"

.SS "uint8_t h_thermo_temp_measure_t::measurement[4]"

.SS "uint8_t h_thermo_temp_measure_t::time_type[8]"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
