.TH "IP_ADDR_T" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IP_ADDR_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <uCXpresso\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBaddr\fP"
.br
.RI "\fIa 32bits unsigned long integer type address \fP"
.ti -1c
.RI "uint8_t \fBaddr8\fP [4]"
.br
.RI "\fIa 4 bytes array address \fP"
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint32_t IP_ADDR_T::addr"

.PP
a 32bits unsigned long integer type address 
.SS "uint8_t IP_ADDR_T::addr8[4]"

.PP
a 4 bytes array address 

.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
