.TH "SYS_ID_T" 3 "Sun Mar 9 2014" "Version v1.0.2" "uCXpresso.BLE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SYS_ID_T \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ble_devinfo\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBmfgId\fP [5]"
.br
.ti -1c
.RI "uint8_t \fBorgId\fP [3]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "uint8_t SYS_ID_T::mfgId[5]"

.SS "uint8_t SYS_ID_T::orgId[3]"


.SH "Author"
.PP 
Generated automatically by Doxygen for uCXpresso\&.BLE from the source code\&.
